# Generated by Django 3.0.8 on 2021-12-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
